import sys
sys.path.append('../') 
from resoprint import Screen


def displayAllColors():
    screen = Screen(rows=37, columns=220, main_symbol="█", main_color="taupe")
    screen.drawButton(row=2,column=2,text=" amaranth ", color="amaranth",width=20)
    screen.drawButton(row=2,column=24,text=" amber ", color="amber",width=20)
    screen.drawButton(row=2,column=46,text=" amethyst ", color="amethyst",width=20)
    screen.drawButton(row=2,column=68,text=" apricot ", color="apricot",width=20)
    screen.drawButton(row=2,column=90,text=" aquamarine ", color="aquamarine",width=20)
    screen.drawButton(row=2,column=112,text=" azure ", color="azure",width=20)
    screen.drawButton(row=2,column=134,text=" babyblue ", color="babyblue",width=20)
    screen.drawButton(row=2,column=156,text=" beige ", color="beige",width=20)
    screen.drawButton(row=2,column=178,text=" brickred ", color="brickred",width=20)
    screen.drawButton(row=2,column=200,text=" black ", color="black",width=20)
    screen.drawButton(row=6,column=2,text=" blue ", color="blue",width=20)
    screen.drawButton(row=6,column=24,text=" bluegreen ", color="bluegreen",width=20)
    screen.drawButton(row=6,column=46,text=" blueviolet ", color="blueviolet",width=20)
    screen.drawButton(row=6,column=68,text=" blush ", color="blush",width=20)
    screen.drawButton(row=6,column=90,text=" bronze ", color="bronze",width=20)
    screen.drawButton(row=6,column=112,text=" brown ", color="brown",width=20)
    screen.drawButton(row=6,column=134,text=" burgundy ", color="burgundy",width=20)
    screen.drawButton(row=6,column=156,text=" byzantium ", color="byzantium",width=20)
    screen.drawButton(row=6,column=178,text=" carmine ", color="carmine",width=20)
    screen.drawButton(row=6,column=200,text=" cerise ", color="cerise",width=20)
    screen.drawButton(row=10,column=2,text=" cerulean ", color="cerulean",width=20)
    screen.drawButton(row=10,column=24,text=" champagne ", color="champagne",width=20)
    screen.drawButton(row=10,column=46,text=" chartreusegreen ", color="chartreusegreen",width=20)
    screen.drawButton(row=10,column=68,text=" chocolate ", color="chocolate",width=20)
    screen.drawButton(row=10,column=90,text=" cobaltblue ", color="cobaltblue",width=20)
    screen.drawButton(row=10,column=112,text=" coffee ", color="coffee",width=20)
    screen.drawButton(row=10,column=134,text=" copper ", color="coffee",width=20)
    screen.drawButton(row=10,column=156,text=" coral ", color="coral",width=20)
    screen.drawButton(row=10,column=178,text=" crimson ", color="crimson",width=20)
    screen.drawButton(row=10,column=200,text=" cyan ", color="cyan",width=20)
    screen.drawButton(row=14,column=2,text=" desertsand ", color="desertsand",width=20)
    screen.drawButton(row=14,column=24,text=" electricblue ", color="electricblue",width=20)
    screen.drawButton(row=14,column=46,text=" emerald ", color="emerald",width=20)
    screen.drawButton(row=14,column=68,text=" erin ", color="erin",width=20)
    screen.drawButton(row=14,column=90,text=" gold ", color="gold",width=20)
    screen.drawButton(row=14,column=112,text=" gray ", color="gray",width=20)
    screen.drawButton(row=14,column=134,text=" green ", color="green",width=20)
    screen.drawButton(row=14,column=156,text=" harlequin ", color="harlequin",width=20)
    screen.drawButton(row=14,column=178,text=" indigo ", color="indigo",width=20)
    screen.drawButton(row=14,column=200,text=" ivory ", color="ivory",width=20)
    screen.drawButton(row=18,column=2,text=" jade ", color="jade",width=20)
    screen.drawButton(row=18,column=24,text=" junglegreen ", color="junglegreen",width=20)
    screen.drawButton(row=18,column=46,text=" lavender ", color="lavender",width=20)
    screen.drawButton(row=18,column=68,text=" lemon ", color="lemon",width=20)
    screen.drawButton(row=18,column=90,text=" lilac ", color="lilac",width=20)
    screen.drawButton(row=18,column=112,text=" lime ", color="lime",width=20)
    screen.drawButton(row=18,column=134,text=" magenta ", color="magenta",width=20)
    screen.drawButton(row=18,column=156,text=" magentarose ", color="magentarose",width=20)
    screen.drawButton(row=18,column=178,text=" maroon ", color="maroon",width=20)
    screen.drawButton(row=18,column=200,text=" mauve ", color="mauve",width=20)
    screen.drawButton(row=22,column=2,text=" navyblue ", color="navyblue",width=20)
    screen.drawButton(row=22,column=24,text=" ochre ", color="ochre",width=20)
    screen.drawButton(row=22,column=46,text=" olive ", color="olive",width=20)
    screen.drawButton(row=22,column=68,text=" orange ", color="orange",width=20)
    screen.drawButton(row=22,column=90,text=" orangered ", color="orangered",width=20)
    screen.drawButton(row=22,column=112,text=" orchid ", color="orchid",width=20)
    screen.drawButton(row=22,column=134,text=" peach ", color="peach",width=20)
    screen.drawButton(row=22,column=156,text=" pear ", color="pear",width=20)
    screen.drawButton(row=22,column=178,text=" periwinkle ", color="periwinkle",width=20)
    screen.drawButton(row=22,column=200,text=" mauve ", color="mauve",width=20)
    screen.drawButton(row=26,column=2,text=" persianblue ", color="persianblue",width=20)
    screen.drawButton(row=26,column=24,text=" pink ", color="pink",width=20)
    screen.drawButton(row=26,column=46,text=" plum ", color="plum",width=20)
    screen.drawButton(row=26,column=68,text=" prussianblue ", color="prussianblue",width=20)
    screen.drawButton(row=26,column=90,text=" puce ", color="puce",width=20)
    screen.drawButton(row=26,column=112,text=" purple ", color="purple",width=20)
    screen.drawButton(row=26,column=134,text=" raspberry ", color="raspberry",width=20)
    screen.drawButton(row=26,column=156,text=" red ", color="red",width=20)
    screen.drawButton(row=26,column=178,text=" redviolet ", color="redviolet",width=20)
    screen.drawButton(row=26,column=200,text=" rose ", color="rose",width=20)
    screen.drawButton(row=30,column=2,text=" ruby ", color="ruby",width=20)
    screen.drawButton(row=30,column=24,text=" salmon ", color="salmon",width=20)
    screen.drawButton(row=30,column=46,text=" sangria ", color="sangria",width=20)
    screen.drawButton(row=30,column=68,text=" sapphire ", color="sapphire",width=20)
    screen.drawButton(row=30,column=90,text=" scarlet ", color="scarlet",width=20)
    screen.drawButton(row=30,column=112,text=" silver ", color="silver",width=20)
    screen.drawButton(row=30,column=134,text=" slategray ", color="slategray",width=20)
    screen.drawButton(row=30,column=156,text=" springbud ", color="springbud",width=20)
    screen.drawButton(row=30,column=178,text=" springgreen ", color="springgreen",width=20)
    screen.drawButton(row=30,column=200,text=" taupe ", color="taupe",width=20)
    screen.drawButton(row=34,column=2,text=" teal ", color="teal",width=20)
    screen.drawButton(row=34,column=24,text=" turquoise ", color="turquoise",width=20)
    screen.drawButton(row=34,column=46,text=" ultramarine ", color="ultramarine",width=20)
    screen.drawButton(row=34,column=68,text=" violet ", color="violet",width=20)
    screen.drawButton(row=34,column=90,text=" viridian ", color="viridian",width=20)
    screen.drawButton(row=34,column=112,text=" white ", color="white",width=20)
    screen.drawButton(row=34,column=134,text=" yellow ", color="yellow",width=20)
    screen.update()

if __name__ == "__main__":
    displayAllColors()